version: '2'
services:

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/config:/config"
      - "./data/prometheus:/data"
    command: --config.file=/config/prometheus.yml --storage.tsdb.path=/data --storage.tsdb.retention=5000h


  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - prometheus
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"