global:
  evaluation_interval: 10s
  scrape_interval: 30s

rule_files:

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: postgres
    static_configs:
      - targets: ['localhost:9187']