global:
  evaluation_interval: 10s
  scrape_interval: 30s

rule_files:

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="prometheus"}'
        - '{job="postgres"}'
        - '{job="node_exporter"}'

    static_configs:
      - targets:
        - '192.168.1.178:9090'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']